Add teleoperation of manipulator from joystick
equinor/isar-turtlebot pull request #79
Opened 2022-02-25 08:21 UTC by knord94

2022-03-28 08:45 UTC, aestene commented
This pull request has automatically been marked as stale as there has been no activity for 30 days. Remove stale label or comment or this will be closed in 7 days.

2022-03-28 10:04 UTC, knord94 commented
Will finish this after Easter.

2022-03-28 10:06 UTC, knord94 commented
> This pull request has automatically been marked as stale as there has been no activity for 30 days. Remove stale label or comment or this will be closed in 7 days.

Please do not close this issue.

2022-04-20 08:50 UTC, Christdej requested changes

2022-04-20 08:50 UTC, Christdej commented on ros_packages/isar_turtlebot_moveit_config/config/chomp_planning.yaml
> +max_recovery_attempts: 5
Add newline

2022-04-20 08:50 UTC, Christdej commented on ros_packages/isar_turtlebot_moveit_config/config/fake_controllers.yaml
> +      - gripper
Add newline

2022-04-20 08:50 UTC, Christdej commented on ros_packages/isar_turtlebot_moveit_config/config/joint_limits.yaml
> +    max_acceleration: 0
Add newline

2022-04-20 08:50 UTC, Christdej commented on ros_packages/isar_turtlebot_moveit_config/config/ompl_planning.yaml
> +  longest_valid_segment_fraction: 0.005
Add newline

2022-04-20 08:50 UTC, Christdej commented on ros_packages/isar_turtlebot_moveit_config/config/sensors_3d.yaml
> +  - {}
Add newline

2022-04-20 08:50 UTC, Christdej commented on ros_packages/isar_turtlebot_moveit_config/launch/gdb_settings.gdb
> +#break trajectory_execution_manager.cpp:228
Add newline

2022-04-21 06:07 UTC, Christdej approved these changes

2022-04-22 06:57 UTC, Christdej approved these changes
LGTM

2022-04-22 07:00 UTC, merged